config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :products do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :comments

  validates :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @comment = Comment.new
  end

  def create
    @product = Product.find(params[:product_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment Added"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Please try again"
      redirect_to :back
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Update Successful"
      redirect_to product_path
    else
      flash[:alert] = "Update Failed"
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

private
  def comment_params
    params.require(:comment).permit(:content, :product_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action except: [:index, :show]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product Added"
      redirect_to products_path
    else
      flash[:alert] = "Please Try Again"
      redirect_to :back
    end
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Update Successful"
      redirect_to products_path
    else
      flash[:alert] = "Update Failed"
      redirect_to :back
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.comments.each do |comment|
      comment.destroy
    end
    @product.destroy
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :description, :price, :user_id, :image)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

protected
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :admin)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "Problem creating your account!"
      redirect_to :back
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@product, @comment] do |f| %>
  <%= f.label :content, "Enter Comment" %>
  <%= f.text_field :content, placeholder: "Enter Comment"%>
  <%= f.text_field :product_id, type: 'hidden', value: @product.id %>
  <%= f.text_field :user_id, type: 'hidden', value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>
<div class="well">
  <%= render "form" %>
</div>

app/views/comments/new.html.erb
<h3>Add New Comment</h3>
<div class="well">
  <%= render "form" %>
</div>

app/views/home/index.html.erb
<h1>Catch of the Day!</h1>

<h3><%= link_to "View All Products", products_path %></h3>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Port Orford Sustainable Seafood</a>
          <% if user_signed_in? %>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li>Logged in as <%= current_user.email %></li>

              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log-out', destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul id="nav-mobile" class="right hide-on-med-and-down">

              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Login', new_user_session_path %></li>
            </ul>
          <% end %>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.text_field :user_id, type: 'hidden', value: current_user.id %>
  <%= f.text_field :name, placeholder: "Product Name" %>
  <%= f.text_field :description, placeholder: "Product Description" %>
  <%= f.number_field :price, :step => 0.01, placeholder: "Product Price" %>
  <%= f.text_field :image, placeholder: "Image URL"%>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<div class="well">
  <%= render "form" %>
</div>

app/views/products/index.html.erb
<h1>All Product Inventory</h1>
<% if current_user && current_user.admin? %>
  <%= link_to "Add New Product", new_product_path, class: "btn" %>
<% end %>

<ul>
  <% @products.each do |product| %>
    <li><h4>
      <%= link_to product.name, product_path(product) %>
    </h4></li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h2>Add New Product</h2>
<div class="well">
  <%= render "form" %>
</div>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<br>
<div class="well">
  <div class="product-image">
    <img src="<%= @product.image %>" alt="" />
  </div>

  <h3>PRODUCT INFORMATION</h3>
  <h4>Price: <%= number_to_currency(@product.price) %></h4>
  <h4>Description: <%= @product.description %></h4>
  <br>

  <% if current_user %>
    <% if @comments %>
      <h5>Comments:</h5>
      <% @comments.each do |comment| %>
        <%= comment.content %>
        <br>
        <% if current_user && current_user.admin? %>
          <%= link_to "Edit Comment", edit_product_comment_path(@product, comment) %> |     <%= link_to "Delete Comment", product_comment_path(@product, comment), :data => {:confirm => "Are you sure?", :method => "delete"} %>
        <% end %>
        <br>
        <br>
      <% end %>
    <% end %>
  <% end %>
  <br>

  <% if current_user %>
    <%= link_to "Add Comment", new_product_comment_path(@product), class: "btn", id: "factory" %>
    <br>
    <br>
  <% end %>
  <% if current_user && current_user.admin? %>
    <%= link_to "Edit Product", edit_product_path(@product), class: "btn" %>
    <%= link_to "Delete Product", product_path(@product), :data => {:confirm => "Are you sure?", :method => "delete"}, class: "btn" %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>